export interface CropItem {
  id: string;
  name: string;
  hindi: string;
  kannada?: string;
  category: CropCategory;
  emoji: string;
}

export type CropCategory =
  | "all"
  | "vegetables"
  | "fruits"
  | "grains"
  | "pulses"
  | "cash_crops"
  | "spices"
  | "horticulture"
  | "flowers";

export const cropCategories: { id: CropCategory; label: string }[] = [
  { id: "all", label: "🌾 All" },
  { id: "grains", label: "🌾 Grains" },
  { id: "vegetables", label: "🥦 Vegetables" },
  { id: "fruits", label: "🍎 Fruits" },
  { id: "pulses", label: "🫘 Pulses" },
  { id: "cash_crops", label: "💰 Cash Crops" },
  { id: "spices", label: "🌶️ Spices" },
  { id: "horticulture", label: "🌴 Horticulture" },
  { id: "flowers", label: "🌸 Flowers" },
];

export const crops: CropItem[] = [
  // ── GRAINS / MILLETS ─────────────────────────────────────────────────────────
  { id: "rice", name: "Rice (Paddy)", hindi: "धान/चावल", kannada: "ಭತ್ತ", category: "grains", emoji: "🌾" },
  { id: "ragi", name: "Ragi (Finger Millet)", hindi: "रागी", kannada: "ರಾಗಿ", category: "grains", emoji: "🌾" },
  { id: "jowar", name: "Jowar (Sorghum)", hindi: "ज्वार", kannada: "ಜೋಳ", category: "grains", emoji: "🌾" },
  { id: "maize", name: "Maize (Corn)", hindi: "मक्का", kannada: "ಮೆಕ್ಕೆ ಜೋಳ", category: "grains", emoji: "🌽" },
  { id: "bajra", name: "Bajra (Pearl Millet)", hindi: "बाजरा", kannada: "ಸಜ್ಜೆ", category: "grains", emoji: "🌾" },
  { id: "wheat", name: "Wheat", hindi: "गेहूँ", kannada: "ಗೋಧಿ", category: "grains", emoji: "🌾" },
  { id: "foxtail_millet", name: "Foxtail Millet (Navane)", hindi: "कंगनी", kannada: "ನವಣೆ", category: "grains", emoji: "🌾" },
  { id: "little_millet", name: "Little Millet (Saame)", hindi: "कुटकी", kannada: "ಸಾಮೆ", category: "grains", emoji: "🌾" },
  { id: "kodo_millet", name: "Kodo Millet (Harka)", hindi: "कोदो", kannada: "ಹಾರಕ", category: "grains", emoji: "🌾" },
  { id: "barley", name: "Barley", hindi: "जौ", kannada: "ಬಾರ್ಲಿ", category: "grains", emoji: "🌾" },

  // ── VEGETABLES ───────────────────────────────────────────────────────────────
  { id: "tomato", name: "Tomato", hindi: "टमाटर", kannada: "ಟೊಮ್ಯಾಟೊ", category: "vegetables", emoji: "🍅" },
  { id: "onion", name: "Onion", hindi: "प्याज", kannada: "ಈರುಳ್ಳಿ", category: "vegetables", emoji: "🧅" },
  { id: "potato", name: "Potato", hindi: "आलू", kannada: "ಆಲೂಗಡ್ಡೆ", category: "vegetables", emoji: "🥔" },
  { id: "brinjal", name: "Brinjal (Eggplant)", hindi: "बैंगन", kannada: "ಬದನೆಕಾಯಿ", category: "vegetables", emoji: "🍆" },
  { id: "okra", name: "Okra (Lady Finger)", hindi: "भिंडी", kannada: "ಬೆಂಡೆಕಾಯಿ", category: "vegetables", emoji: "🌿" },
  { id: "cabbage", name: "Cabbage", hindi: "पत्तागोभी", kannada: "ಎಲೆಕೋಸು", category: "vegetables", emoji: "🥬" },
  { id: "cauliflower", name: "Cauliflower", hindi: "फूलगोभी", kannada: "ಹೂಕೋಸು", category: "vegetables", emoji: "🥦" },
  { id: "capsicum", name: "Capsicum (Bell Pepper)", hindi: "शिमला मिर्च", kannada: "ದೊಡ್ಡ ಮೆಣಸಿನಕಾಯಿ", category: "vegetables", emoji: "🫑" },
  { id: "green_chili", name: "Green Chili", hindi: "हरी मिर्च", kannada: "ಹಸಿರು ಮೆಣಸಿನಕಾಯಿ", category: "vegetables", emoji: "🌶️" },
  { id: "cucumber", name: "Cucumber", hindi: "खीरा", kannada: "ಸೌತೆಕಾಯಿ", category: "vegetables", emoji: "🥒" },
  { id: "carrot", name: "Carrot", hindi: "गाजर", kannada: "ಗಾಜರು", category: "vegetables", emoji: "🥕" },
  { id: "beans", name: "Green Beans", hindi: "फलियाँ", kannada: "ಹುರಳಿಕಾಯಿ", category: "vegetables", emoji: "🫘" },
  { id: "pumpkin", name: "Pumpkin", hindi: "कद्दू", kannada: "ಕುಂಬಳಕಾಯಿ", category: "vegetables", emoji: "🎃" },
  { id: "bitter_gourd", name: "Bitter Gourd (Karela)", hindi: "करेला", kannada: "ಹಾಗಲಕಾಯಿ", category: "vegetables", emoji: "🥒" },
  { id: "bottle_gourd", name: "Bottle Gourd (Lauki)", hindi: "लौकी", kannada: "ಸೋರೆಕಾಯಿ", category: "vegetables", emoji: "🍐" },
  { id: "ridge_gourd", name: "Ridge Gourd", hindi: "तोरई", kannada: "ಹೀರೆಕಾಯಿ", category: "vegetables", emoji: "🥒" },
  { id: "ash_gourd", name: "Ash Gourd (Boodhu Kumbalakai)", hindi: "पेठा", kannada: "ಬೂದು ಕುಂಬಳ", category: "vegetables", emoji: "🎃" },
  { id: "spinach", name: "Spinach (Palak)", hindi: "पालक", kannada: "ಪಾಲಕ", category: "vegetables", emoji: "🥬" },
  { id: "radish", name: "Radish (Moolangi)", hindi: "मूली", kannada: "ಮೂಲಂಗಿ", category: "vegetables", emoji: "🥕" },
  { id: "beetroot", name: "Beetroot", hindi: "चुकंदर", kannada: "ಬೀಟ್‌ರೂಟ್", category: "vegetables", emoji: "🫐" },
  { id: "garlic", name: "Garlic", hindi: "लहसुन", kannada: "ಬೆಳ್ಳುಳ್ಳಿ", category: "vegetables", emoji: "🧄" },
  { id: "ginger", name: "Ginger", hindi: "अदरक", kannada: "ಶುಂಠಿ", category: "vegetables", emoji: "🫚" },
  { id: "drumstick", name: "Drumstick (Moringa)", hindi: "सहजन", kannada: "ನುಗ್ಗೆಕಾಯಿ", category: "vegetables", emoji: "🌿" },
  { id: "dolichos_bean", name: "Field Beans (Avare)", hindi: "शेम", kannada: "ಅವರೆಕಾಯಿ", category: "vegetables", emoji: "🫘" },
  { id: "cluster_bean", name: "Cluster Beans (Guar)", hindi: "गुवार", kannada: "ಗೋರಿಕಾಯಿ", category: "vegetables", emoji: "🫘" },
  { id: "sweet_potato", name: "Sweet Potato", hindi: "शकरकंद", kannada: "ಸಿಹಿ ಗೆಣಸು", category: "vegetables", emoji: "🍠" },
  { id: "yam", name: "Yam (Suran)", hindi: "जिमीकंद", kannada: "ಕೇಸು/ಗೆಣಸು", category: "vegetables", emoji: "🥔" },
  { id: "colocasia", name: "Colocasia (Taro)", hindi: "अरबी", kannada: "ಕೇಪಳ", category: "vegetables", emoji: "🥔" },

  // ── FRUITS ───────────────────────────────────────────────────────────────────
  { id: "mango", name: "Mango", hindi: "आम", kannada: "ಮಾವು", category: "fruits", emoji: "🥭" },
  { id: "banana", name: "Banana", hindi: "केला", kannada: "ಬಾಳೆಹಣ್ಣು", category: "fruits", emoji: "🍌" },
  { id: "grapes", name: "Grapes", hindi: "अंगूर", kannada: "ದ್ರಾಕ್ಷಿ", category: "fruits", emoji: "🍇" },
  { id: "papaya", name: "Papaya", hindi: "पपीता", kannada: "ಪಪ್ಪಾಯಿ", category: "fruits", emoji: "🍈" },
  { id: "watermelon", name: "Watermelon", hindi: "तरबूज", kannada: "ಕಲ್ಲಂಗಡಿ", category: "fruits", emoji: "🍉" },
  { id: "guava", name: "Guava", hindi: "अमरूद", kannada: "ಸೀಬೆ", category: "fruits", emoji: "🍐" },
  { id: "lemon", name: "Lemon", hindi: "नींबू", kannada: "ನಿಂಬೆ", category: "fruits", emoji: "🍋" },
  { id: "orange", name: "Orange / Mosambi", hindi: "संतरा", kannada: "ಕಿತ್ತಳೆ", category: "fruits", emoji: "🍊" },
  { id: "pomegranate", name: "Pomegranate", hindi: "अनार", kannada: "ದಾಳಿಂಬೆ", category: "fruits", emoji: "🫐" },
  { id: "sapota", name: "Sapota (Chikku)", hindi: "चीकू", kannada: "ಸಪೋಟ", category: "fruits", emoji: "🍑" },
  { id: "pineapple", name: "Pineapple", hindi: "अनानास", kannada: "ಅನಾನಸ", category: "fruits", emoji: "🍍" },
  { id: "apple", name: "Apple", hindi: "सेब", kannada: "ಸೇಬು", category: "fruits", emoji: "🍎" },
  { id: "jackfruit", name: "Jackfruit (Halasu)", hindi: "कटहल", kannada: "ಹಲಸು", category: "fruits", emoji: "🍈" },
  { id: "fig", name: "Fig (Anjura)", hindi: "अंजीर", kannada: "ಅಂಜೂರ", category: "fruits", emoji: "🍑" },
  { id: "tamarind", name: "Tamarind (Hunise)", hindi: "इमली", kannada: "ಹುಣಸೆ", category: "fruits", emoji: "🟤" },
  { id: "gooseberry", name: "Gooseberry (Amla)", hindi: "आंवला", kannada: "ನೆಲ್ಲಿಕಾಯಿ", category: "fruits", emoji: "🍈" },

  // ── PULSES ───────────────────────────────────────────────────────────────────
  { id: "tur", name: "Pigeon Pea (Tur/Arhar)", hindi: "तूर/अरहर", kannada: "ತೊಗರಿ", category: "pulses", emoji: "🫘" },
  { id: "chickpea", name: "Chickpea (Chana)", hindi: "चना", kannada: "ಕಡಲೆ", category: "pulses", emoji: "🫘" },
  { id: "green_gram", name: "Green Gram (Moong)", hindi: "मूँग", kannada: "ಹೆಸರು", category: "pulses", emoji: "🫘" },
  { id: "black_gram", name: "Black Gram (Urad)", hindi: "उड़द", kannada: "ಉದ್ದು", category: "pulses", emoji: "🫘" },
  { id: "lentil", name: "Lentil (Masoor)", hindi: "मसूर", kannada: "ಮಸೂರ", category: "pulses", emoji: "🫘" },
  { id: "horse_gram", name: "Horse Gram (Hurali)", hindi: "कुलथी", kannada: "ಹುರಳಿ", category: "pulses", emoji: "🫘" },
  { id: "cowpea", name: "Cowpea (Alasande)", hindi: "लोबिया", kannada: "ಅಲಸಂದೆ", category: "pulses", emoji: "🫘" },
  { id: "field_pea", name: "Field Pea (Vatana)", hindi: "मटर", kannada: "ವಟಾಣ", category: "pulses", emoji: "🫘" },
  { id: "bengal_gram", name: "Bengal Gram (Kala Chana)", hindi: "काला चना", kannada: "ಕಡಲೆ", category: "pulses", emoji: "🫘" },
  { id: "moth_bean", name: "Moth Bean (Mataki)", hindi: "मोठ", kannada: "ಮೊಠ", category: "pulses", emoji: "🫘" },

  // ── CASH CROPS ───────────────────────────────────────────────────────────────
  { id: "sugarcane", name: "Sugarcane", hindi: "गन्ना", kannada: "ಕಬ್ಬು", category: "cash_crops", emoji: "🎋" },
  { id: "cotton", name: "Cotton", hindi: "कपास", kannada: "ಹತ್ತಿ", category: "cash_crops", emoji: "🌿" },
  { id: "groundnut", name: "Groundnut (Peanut)", hindi: "मूँगफली", kannada: "ಶೇಂಗಾ", category: "cash_crops", emoji: "🥜" },
  { id: "sunflower", name: "Sunflower", hindi: "सूरजमुखी", kannada: "ಸೂರ್ಯಕಾಂತಿ", category: "cash_crops", emoji: "🌻" },
  { id: "soybean", name: "Soybean", hindi: "सोयाबीन", kannada: "ಸೋಯಾ", category: "cash_crops", emoji: "🌿" },
  { id: "sesame", name: "Sesame (Til)", hindi: "तिल", kannada: "ಎಳ್ಳು", category: "cash_crops", emoji: "🌿" },
  { id: "mustard", name: "Mustard (Sasive)", hindi: "सरसों", kannada: "ಸಾಸಿವೆ", category: "cash_crops", emoji: "🌿" },
  { id: "safflower", name: "Safflower (Kusuma)", hindi: "कुसुम", kannada: "ಕುಸುಬೆ", category: "cash_crops", emoji: "🌼" },
  { id: "castor", name: "Castor (Haralu)", hindi: "अरंडी", kannada: "ಹರಳು", category: "cash_crops", emoji: "🌿" },
  { id: "linseed", name: "Linseed (Agase)", hindi: "अलसी", kannada: "ಅಗಸೆ", category: "cash_crops", emoji: "🌿" },
  { id: "tobacco", name: "Tobacco (Virginia/Bidi)", hindi: "तंबाकू", kannada: "ತಂಬಾಕು", category: "cash_crops", emoji: "🌿" },
  { id: "jute", name: "Jute", hindi: "जूट", kannada: "ಸೆಣಬು", category: "cash_crops", emoji: "🌿" },

  // ── SPICES ───────────────────────────────────────────────────────────────────
  { id: "turmeric", name: "Turmeric (Arishina)", hindi: "हल्दी", kannada: "ಅರಿಶಿನ", category: "spices", emoji: "🟡" },
  { id: "chilli_dry", name: "Red Chilli (Dry)", hindi: "लाल मिर्च", kannada: "ಒಣ ಮೆಣಸಿನಕಾಯಿ", category: "spices", emoji: "🌶️" },
  { id: "pepper", name: "Black Pepper (Menasina)", hindi: "काली मिर्च", kannada: "ಮೆಣಸು", category: "spices", emoji: "🫙" },
  { id: "cardamom", name: "Cardamom (Elakki)", hindi: "इलायची", kannada: "ಏಲಕ್ಕಿ", category: "spices", emoji: "🫙" },
  { id: "coriander", name: "Coriander (Kottambari)", hindi: "धनिया", kannada: "ಕೊತ್ತಂಬರಿ", category: "spices", emoji: "🌿" },
  { id: "fenugreek", name: "Fenugreek (Menthya)", hindi: "मेथी", kannada: "ಮೆಂತ್ಯ", category: "spices", emoji: "🌿" },
  { id: "cumin", name: "Cumin (Jeerige)", hindi: "जीरा", kannada: "ಜೀರಿಗೆ", category: "spices", emoji: "🫙" },
  { id: "ajwain", name: "Carom Seeds (Oma)", hindi: "अजवाइन", kannada: "ಓಮ", category: "spices", emoji: "🫙" },
  { id: "nutmeg", name: "Nutmeg (Jaiphal)", hindi: "जायफल", kannada: "ಜಾಯಿಕಾಯಿ", category: "spices", emoji: "🫙" },
  { id: "vanilla", name: "Vanilla", hindi: "वेनिला", kannada: "ವೆನಿಲ್ಲಾ", category: "spices", emoji: "🌿" },

  // ── HORTICULTURE ─────────────────────────────────────────────────────────────
  { id: "coconut", name: "Coconut (Tengina)", hindi: "नारियल", kannada: "ತೆಂಗಿನಕಾಯಿ", category: "horticulture", emoji: "🥥" },
  { id: "arecanut", name: "Arecanut (Adike/Betel Nut)", hindi: "सुपारी", kannada: "ಅಡಿಕೆ", category: "horticulture", emoji: "🌴" },
  { id: "coffee", name: "Coffee (Arabica/Robusta)", hindi: "कॉफ़ी", kannada: "ಕಾಫಿ", category: "horticulture", emoji: "☕" },
  { id: "tea", name: "Tea", hindi: "चाय", kannada: "ಚಹಾ", category: "horticulture", emoji: "🍵" },
  { id: "rubber", name: "Rubber", hindi: "रबर", kannada: "ರಬ್ಬರ್", category: "horticulture", emoji: "🌲" },
  { id: "cashew", name: "Cashew (Godambi)", hindi: "काजू", kannada: "ಗೋಡಂಬಿ", category: "horticulture", emoji: "🥜" },
  { id: "cocoa", name: "Cocoa", hindi: "कोको", kannada: "ಕೋಕೋ", category: "horticulture", emoji: "🍫" },
  { id: "betelvine", name: "Betel Vine (Veelyada Ele)", hindi: "पान", kannada: "ವೀಳ್ಯದ ಎಲೆ", category: "horticulture", emoji: "🌿" },
  { id: "silk_cotton", name: "Mulberry (Sericulture)", hindi: "शहतूत", kannada: "ಹಿಪ್ಪುನೇರಳೆ", category: "horticulture", emoji: "🌿" },
  { id: "eucalyptus", name: "Eucalyptus (Timber)", hindi: "नीलगिरि", kannada: "ನೀಲಗಿರಿ", category: "horticulture", emoji: "🌲" },

  // ── FLOWERS ──────────────────────────────────────────────────────────────────
  { id: "marigold", name: "Marigold (Zende Hoovu)", hindi: "गेंदा", kannada: "ಚೆಂಡು ಹೂ", category: "flowers", emoji: "🌼" },
  { id: "rose", name: "Rose", hindi: "गुलाब", kannada: "ಗುಲಾಬಿ", category: "flowers", emoji: "🌹" },
  { id: "jasmine", name: "Jasmine (Mallige)", hindi: "चमेली", kannada: "ಮಲ್ಲಿಗೆ", category: "flowers", emoji: "🌸" },
  { id: "chrysanthemum", name: "Chrysanthemum (Chamanthi)", hindi: "गुलदाउदी", kannada: "ಚಾಮಂತಿ", category: "flowers", emoji: "🌸" },
  { id: "crossandra", name: "Crossandra (Kanakambara)", hindi: "कनकाम्बरा", kannada: "ಕನಕಾಂಬರ", category: "flowers", emoji: "🌼" },
  { id: "gerbera", name: "Gerbera (Cut Flower)", hindi: "गेरबेरा", kannada: "ಗೆರ್ಬೆರಾ", category: "flowers", emoji: "🌺" },
];

export const indianCities = [
  // Karnataka — comprehensive
  "Bengaluru, Karnataka",
  "Mysuru, Karnataka",
  "Hubli, Karnataka",
  "Dharwad, Karnataka",
  "Belagavi, Karnataka",
  "Mangaluru, Karnataka",
  "Kalaburagi, Karnataka",
  "Ballari, Karnataka",
  "Tumakuru, Karnataka",
  "Shivamogga, Karnataka",
  "Raichur, Karnataka",
  "Bidar, Karnataka",
  "Vijayapura, Karnataka",
  "Davangere, Karnataka",
  "Hassan, Karnataka",
  "Chitradurga, Karnataka",
  "Udupi, Karnataka",
  "Chikkamagaluru, Karnataka",
  "Kolar, Karnataka",
  "Bagalkot, Karnataka",
  "Gadag, Karnataka",
  "Haveri, Karnataka",
  "Koppal, Karnataka",
  "Yadgir, Karnataka",
  "Chamarajanagar, Karnataka",
  "Mandya, Karnataka",
  "Kodagu, Karnataka",
  "Chikkaballapur, Karnataka",
  "Ramnagara, Karnataka",
  "Robertsonpet, Karnataka",
  // Major metros & agri hubs
  "Mumbai, Maharashtra",
  "Delhi, Delhi",
  "Hyderabad, Telangana",
  "Ahmedabad, Gujarat",
  "Chennai, Tamil Nadu",
  "Kolkata, West Bengal",
  "Pune, Maharashtra",
  "Jaipur, Rajasthan",
  "Lucknow, Uttar Pradesh",
  "Nagpur, Maharashtra",
  "Indore, Madhya Pradesh",
  "Bhopal, Madhya Pradesh",
  "Visakhapatnam, Andhra Pradesh",
  "Patna, Bihar",
  "Vadodara, Gujarat",
  "Ludhiana, Punjab",
  "Agra, Uttar Pradesh",
  "Nashik, Maharashtra",
  "Amritsar, Punjab",
  "Coimbatore, Tamil Nadu",
  "Vijayawada, Andhra Pradesh",
  "Madurai, Tamil Nadu",
  "Raipur, Chhattisgarh",
  "Chandigarh, Chandigarh",
  "Guwahati, Assam",
  "Solapur, Maharashtra",
  "Tiruchirappalli, Tamil Nadu",
  "Kolhapur, Maharashtra",
  "Sangli, Maharashtra",
  "Kolhapur, Maharashtra",
  "Warangal, Telangana",
  "Nellore, Andhra Pradesh",
  "Kurnool, Andhra Pradesh",
  "Tirupati, Andhra Pradesh",
  "Ernakulam, Kerala",
  "Thiruvananthapuram, Kerala",
  "Kozhikode, Kerala",
  "Thrissur, Kerala",
  "Surat, Gujarat",
  "Rajkot, Gujarat",
  "Jodhpur, Rajasthan",
  "Bikaner, Rajasthan",
  "Jodhpur, Rajasthan",
  "Varanasi, Uttar Pradesh",
  "Kanpur, Uttar Pradesh",
  "Meerut, Uttar Pradesh",
];
