project_id = "bfotzjkiymcplnatgxzv"

[functions.diagnose-plant]
verify_jwt = false

[functions.chat]
verify_jwt = false

[functions.weather]
verify_jwt = false

[functions.soil-analysis]
verify_jwt = false

[functions.price-forecast]
verify_jwt = false

[functions.farmer-blog]
verify_jwt = false