export interface LaborerProfile {
  id: string;
  name: string;
  mobile: string;
  village: string;
  lat: number;
  lng: number;
  distance?: number; // Calculated on the fly
  age: number;
  gender: string;
  primarySkill: string;
  secondarySkill?: string;
  availableFrom: string;
  availableTo: string;
  shift: 'day' | 'night' | 'both';
  wage: number;
  experience: number;
  languages: string[];
  bio: string;
  verified: boolean;
  hiredCount: number;
  rating: number;
}

export const dummyLaborers: LaborerProfile[] = [
  {
    id: "l1",
    name: "Chirag Patil",
    mobile: "+91 9876543210",
    village: "Shiggaon",
    lat: 14.9912,
    lng: 75.2234,
    age: 28,
    gender: "Male",
    primarySkill: "irrigation",
    secondarySkill: "general_labor",
    availableFrom: new Date().toISOString(),
    availableTo: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    shift: "day",
    wage: 450,
    experience: 5,
    languages: ["Kannada", "Hindi"],
    bio: "Chirag is a reliable agricultural worker with 5 years of experience specializing in irrigation and water management.",
    verified: true,
    hiredCount: 12,
    rating: 4.8
  },
  {
    id: "l2",
    name: "Keshav Gowda",
    mobile: "+91 8765432109",
    village: "Haveri",
    lat: 14.7952,
    lng: 75.4011,
    age: 35,
    gender: "Male",
    primarySkill: "machinery",
    secondarySkill: "ploughing",
    availableFrom: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(),
    availableTo: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString(),
    shift: "both",
    wage: 800,
    experience: 10,
    languages: ["Kannada", "Telugu"],
    bio: "Keshav is highly skilled in operating tractors and farm machinery, ensuring precise and efficient land preparation.",
    verified: true,
    hiredCount: 34,
    rating: 4.9
  },
  {
    id: "l3",
    name: "Lingaraju Hubli",
    mobile: "+91 7654321098",
    village: "Kundgol",
    lat: 15.2530,
    lng: 75.2477,
    age: 42,
    gender: "Male",
    primarySkill: "harvesting",
    secondarySkill: "weeding",
    availableFrom: new Date().toISOString(),
    availableTo: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
    shift: "day",
    wage: 500,
    experience: 15,
    languages: ["Kannada"],
    bio: "A veteran in crop harvesting, Lingaraju brings 15 years of dedicated farm labor experience.",
    verified: false,
    hiredCount: 5,
    rating: 4.2
  },
  {
    id: "l4",
    name: "Amar Desai",
    mobile: "+91 6543210987",
    village: "Dharwad",
    lat: 15.4589,
    lng: 75.0078,
    age: 24,
    gender: "Male",
    primarySkill: "pesticide",
    secondarySkill: "sowing",
    availableFrom: new Date().toISOString(),
    availableTo: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    shift: "night",
    wage: 600,
    experience: 2,
    languages: ["Kannada", "English", "Hindi"],
    bio: "Amar is a young, energetic worker familiar with modern pesticide and fertilizer application techniques.",
    verified: true,
    hiredCount: 8,
    rating: 4.5
  },
  {
    id: "l5",
    name: "Raju Hiremath",
    mobile: "+91 5432109876",
    village: "Hubballi",
    lat: 15.3647,
    lng: 75.1240,
    age: 50,
    gender: "Male",
    primarySkill: "horticulture",
    secondarySkill: "post_harvest",
    availableFrom: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    availableTo: new Date(Date.now() + 20 * 24 * 60 * 60 * 1000).toISOString(),
    shift: "day",
    wage: 550,
    experience: 25,
    languages: ["Kannada", "Hindi"],
    bio: "With over 25 years in horticulture, Raju specializes in fruits and vegetable cultivation and storage.",
    verified: true,
    hiredCount: 56,
    rating: 5.0
  },
  {
    id: "l6",
    name: "Nagraj Kulkarni",
    mobile: "+91 9988776655",
    village: "Ranebennur",
    lat: 14.6150,
    lng: 75.6178,
    age: 30,
    gender: "Male",
    primarySkill: "sericulture",
    secondarySkill: "general_labor",
    availableFrom: new Date().toISOString(),
    availableTo: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000).toISOString(),
    shift: "day",
    wage: 500,
    experience: 7,
    languages: ["Kannada"],
    bio: "Nagraj has 7 years of deep expertise in silk and mulberry farm maintenance.",
    verified: false,
    hiredCount: 3,
    rating: 4.0
  },
  {
    id: "l7",
    name: "Suresh Bhat",
    mobile: "+91 9123456780",
    village: "Navalgund",
    lat: 15.5600,
    lng: 75.3600,
    age: 40,
    gender: "Male",
    primarySkill: "sowing",
    secondarySkill: "general_labor",
    availableFrom: new Date().toISOString(),
    availableTo: new Date(Date.now() + 15 * 24 * 60 * 60 * 1000).toISOString(),
    shift: "day",
    wage: 400,
    experience: 12,
    languages: ["Kannada"],
    bio: "Suresh is highly skilled in sowing and transplanting across multiple crop types.",
    verified: true,
    hiredCount: 22,
    rating: 4.6
  },
  {
    id: "l8",
    name: "Manjula Y",
    mobile: "+91 9234567891",
    village: "Kalghatgi",
    lat: 15.1800,
    lng: 74.9700,
    age: 32,
    gender: "Female",
    primarySkill: "weeding",
    secondarySkill: "harvesting",
    availableFrom: new Date().toISOString(),
    availableTo: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    shift: "day",
    wage: 350,
    experience: 6,
    languages: ["Kannada"],
    bio: "Manjula is a fast and thorough worker, specializing in weeding and careful crop harvesting.",
    verified: true,
    hiredCount: 14,
    rating: 4.7
  },
  {
    id: "l9",
    name: "Prakash Reddy",
    mobile: "+91 9345678902",
    village: "Ron",
    lat: 15.6900,
    lng: 75.7300,
    age: 45,
    gender: "Male",
    primarySkill: "ploughing",
    secondarySkill: "machinery",
    availableFrom: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    availableTo: new Date(Date.now() + 12 * 24 * 60 * 60 * 1000).toISOString(),
    shift: "both",
    wage: 700,
    experience: 20,
    languages: ["Kannada", "Telugu"],
    bio: "Prakash operates heavy farm machinery and excels in land preparation.",
    verified: true,
    hiredCount: 41,
    rating: 4.9
  },
  {
    id: "l10",
    name: "Vinod Kumar",
    mobile: "+91 9456789013",
    village: "Nargund",
    lat: 15.7200,
    lng: 75.3800,
    age: 26,
    gender: "Male",
    primarySkill: "poultry",
    secondarySkill: "general_labor",
    availableFrom: new Date().toISOString(),
    availableTo: new Date(Date.now() + 20 * 24 * 60 * 60 * 1000).toISOString(),
    shift: "day",
    wage: 450,
    experience: 3,
    languages: ["Kannada", "Hindi"],
    bio: "Vinod manages animal husbandry and poultry with great care.",
    verified: false,
    hiredCount: 2,
    rating: 4.0
  },
  {
    id: "l11",
    name: "Anil Naik",
    mobile: "+91 9567890124",
    village: "Shirahatti",
    lat: 15.2300,
    lng: 75.5800,
    age: 38,
    gender: "Male",
    primarySkill: "greenhouse",
    secondarySkill: "horticulture",
    availableFrom: new Date().toISOString(),
    availableTo: new Date(Date.now() + 8 * 24 * 60 * 60 * 1000).toISOString(),
    shift: "day",
    wage: 600,
    experience: 8,
    languages: ["Kannada"],
    bio: "Anil has 8 years of experience managing polyhouse environments for vegetables.",
    verified: true,
    hiredCount: 18,
    rating: 4.5
  },
  {
    id: "l12",
    name: "Lakshmi D",
    mobile: "+91 9678901235",
    village: "Mundargi",
    lat: 15.2000,
    lng: 75.8800,
    age: 29,
    gender: "Female",
    primarySkill: "post_harvest",
    secondarySkill: "general_labor",
    availableFrom: new Date().toISOString(),
    availableTo: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000).toISOString(),
    shift: "day",
    wage: 350,
    experience: 5,
    languages: ["Kannada"],
    bio: "Lakshmi specializes in sorting, packing, and safe storage of harvested crops.",
    verified: true,
    hiredCount: 11,
    rating: 4.8
  },
  {
    id: "l13",
    name: "Ramesh P",
    mobile: "+91 9789012346",
    village: "Hubballi",
    lat: 15.3600,
    lng: 75.1400,
    age: 34,
    gender: "Male",
    primarySkill: "general_labor",
    secondarySkill: "irrigation",
    availableFrom: new Date().toISOString(),
    availableTo: new Date(Date.now() + 6 * 24 * 60 * 60 * 1000).toISOString(),
    shift: "night",
    wage: 500,
    experience: 6,
    languages: ["Kannada", "Hindi"],
    bio: "Ramesh is available for all-around farm duties and night-time irrigation.",
    verified: true,
    hiredCount: 29,
    rating: 4.4
  },
  {
    id: "l14",
    name: "Muthu Swami",
    mobile: "+91 9890123457",
    village: "Gokak",
    lat: 16.1600,
    lng: 74.8300,
    age: 48,
    gender: "Male",
    primarySkill: "machinery",
    secondarySkill: "harvesting",
    availableFrom: new Date().toISOString(),
    availableTo: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
    shift: "day",
    wage: 850,
    experience: 20,
    languages: ["Kannada", "Tamil"],
    bio: "Muthu is a master tractor operator, handling complex harvesting machinery safely.",
    verified: true,
    hiredCount: 52,
    rating: 5.0
  },
  {
    id: "l15",
    name: "Shivakumar T",
    mobile: "+91 9901234568",
    village: "Savadatti",
    lat: 15.7700,
    lng: 75.1100,
    age: 22,
    gender: "Male",
    primarySkill: "pesticide",
    secondarySkill: "weeding",
    availableFrom: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(),
    availableTo: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    shift: "both",
    wage: 550,
    experience: 1,
    languages: ["Kannada"],
    bio: "Shivakumar is a strong fresher, eager to help with spraying and weeding tasks.",
    verified: false,
    hiredCount: 1,
    rating: 4.0
  },
  {
    id: "l16",
    name: "Parvati S",
    mobile: "+91 9012345679",
    village: "Bailhongal",
    lat: 15.8100,
    lng: 74.8500,
    age: 36,
    gender: "Female",
    primarySkill: "sowing",
    secondarySkill: "weeding",
    availableFrom: new Date().toISOString(),
    availableTo: new Date(Date.now() + 12 * 24 * 60 * 60 * 1000).toISOString(),
    shift: "day",
    wage: 400,
    experience: 10,
    languages: ["Kannada", "Marathi"],
    bio: "Parvati has 10 years of experience in rapid and accurate sowing.",
    verified: true,
    hiredCount: 25,
    rating: 4.9
  },
  {
    id: "l17",
    name: "Ganesh Hegde",
    mobile: "+91 8123456789",
    village: "Sirsi",
    lat: 14.6100,
    lng: 74.8300,
    age: 41,
    gender: "Male",
    primarySkill: "horticulture",
    secondarySkill: "sericulture",
    availableFrom: new Date().toISOString(),
    availableTo: new Date(Date.now() + 20 * 24 * 60 * 60 * 1000).toISOString(),
    shift: "day",
    wage: 650,
    experience: 15,
    languages: ["Kannada", "English"],
    bio: "Ganesh is an expert in arecanut and spice horticulture.",
    verified: true,
    hiredCount: 38,
    rating: 4.8
  },
  {
    id: "l18",
    name: "Ravi G",
    mobile: "+91 8234567890",
    village: "Yellapur",
    lat: 14.9600,
    lng: 74.7100,
    age: 27,
    gender: "Male",
    primarySkill: "general_labor",
    secondarySkill: "post_harvest",
    availableFrom: new Date().toISOString(),
    availableTo: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000).toISOString(),
    shift: "night",
    wage: 450,
    experience: 4,
    languages: ["Kannada"],
    bio: "Ravi can handle loading, unloading, and farm security at night.",
    verified: false,
    hiredCount: 7,
    rating: 4.1
  },
  {
    id: "l19",
    name: "Sunil K",
    mobile: "+91 8345678901",
    village: "Haliyal",
    lat: 15.3300,
    lng: 74.7500,
    age: 31,
    gender: "Male",
    primarySkill: "irrigation",
    secondarySkill: "machinery",
    availableFrom: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    availableTo: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000).toISOString(),
    shift: "both",
    wage: 600,
    experience: 8,
    languages: ["Kannada", "Hindi"],
    bio: "Sunil is proficient with water pumps, pipe laying, and minor machinery repairs.",
    verified: true,
    hiredCount: 16,
    rating: 4.6
  },
  {
    id: "l20",
    name: "Mahesh M",
    mobile: "+91 8456789012",
    village: "Ranebennur",
    lat: 14.6200,
    lng: 75.6200,
    age: 55,
    gender: "Male",
    primarySkill: "poultry",
    secondarySkill: "general_labor",
    availableFrom: new Date().toISOString(),
    availableTo: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
    shift: "day",
    wage: 400,
    experience: 30,
    languages: ["Kannada"],
    bio: "A highly experienced farmhand who treats animals with the utmost care.",
    verified: true,
    hiredCount: 64,
    rating: 4.9
  }
];

// Helper to calculate distance between two coords in km
export function getDistanceFromLatLonInKm(lat1: number, lon1: number, lat2: number, lon2: number) {
  const R = 6371; // Radius of the earth in km
  const dLat = deg2rad(lat2 - lat1);  
  const dLon = deg2rad(lon2 - lon1); 
  const a = 
    Math.sin(dLat/2) * Math.sin(dLat/2) +
    Math.cos(deg2rad(lat1)) * Math.cos(deg2rad(lat2)) * 
    Math.sin(dLon/2) * Math.sin(dLon/2)
    ; 
  const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1-a)); 
  const d = R * c; // Distance in km
  return d;
}

function deg2rad(deg: number) {
  return deg * (Math.PI/180);
}
